name: Github Action Runner Workflow /pipeline for Node Enviroment Setup

on:
  push:
    branches:
      - main
      - master

jobs:
  CI-Pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: "Setup Node Enviroment"
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: "Check Node version"
        run: node --version

      - name: "Clone React Repo"
        uses: actions/checkout@v2

      - name: "Install All React Dependancies"
        run: npm install

      - name: "Show React Directories"
        run: ls

      - name: "Setup React Build"
        run: npm run build
